---
title: "Cartogram Mapping and Application to Cancer Data."
output: html_document
fig_caption: yes
number_sections: false
fontsize: 11pt
bibliography: reviewbib.bib
biblio-style: vancouver
link-citations: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<!--
Author notes:
6000 words maximum.
focused  application  of  literature  to address  a  relevant  clinical  issue:
Mapping cancer outcomes
Cartogram applications should point to examples of cancer outcomes, with the main cartogram section discussing sources considered in grey literature review. Examples of political areas may be considered if cancer data is aggregated at these levels.

Future steps should consider applications not currently utilised for cancer outcome displays, where their use may improve decision making
-->


## Abstract

Utilising maps to present statistics has been widely used, for centuries.
Connecting the data to the geographical representation of areas that are already familiar.
It is not enough to be recognisable, if the value of the statistic cannot be seen. Cancer outcomes directly relate to the people living within a geographical area. In situations where the people are of interest, not the land they live on, it is reasonable to explore views that enhance the communication of the cancer outcomes. This has spurred innovations over the previous centuries to enhance the shapes and maps presented to effectively communicate cancer outcomes.


## Disease mapping

### Choropleth Map (Steff)

Choropleth mapping methods effectively explore a relationship across a geographical space.
Thematic maps involve drawing administrative or other boundaries and filling the regions with colours, symbols or patterns to present levels, or rates, of the information communicated. @CIBMUK believes these 'representations are highly intuitive' as the familiar shapes help those looking at the maps to visually infer spatial relationships. 
The visualisations are true maps, used for visual inspection and can help to direct hypotheses about the spatial patterns across the physical space. 
These true maps rely on visual perception, a fallible metric as it can 'weight the shades from the largest areas more heavily.' The inferences derived from visual inspection, and the hypotheses developed can suffer from 'bias'. The use of thematic disease mapping was motivated by a 'desire to evaluate geographical patterns' @DMAHP. This technique has been seen as a 'trigger for questions' which drives research of spatial distributions. @MACM also recognise the intuition that can be derived from choropleths with the critique that they must be 'validated by rigorous statistical analyses.' 

In epidemiology, choropleths are often used as a mapping tool in the study of the spatial distribution. 
Almost 100 years of cancer maps have explored the US and the UK with increased effectiveness in presentation of unbiased rates. 
The data collection methods, and administrative control within regions lends itself choropleth visualisation, for the presentation of cancer mortality rates across regions. Mortality rates are now presented as relative rates of risk across the population, an age adjusted to correct for the proportion of old people. Howe [-@HEDP] describes Stocks development of the standardised mortality ratios through the 1930s. The choropleth maps presented levels of cancer via hatchings on a black and white scale. 


@DMAHP cites Cruickshank's (1947) discussion of using visuals as 'formal statistical assessment of the spatial pattern' as a major advancement.

@HEDP considered maps a research tool, dots maps use spots, choropleths and thematic maps shade areas and isopleths use isolines. These  techniques were commonly used before the advent of computer-assisted cartography.



<!--
Current atlases utilising choropleth methods 
- include Australia: 

Clear examples of:
White paper example for published Atlases
-methods they use

cites: Cancer Mortality Atlas of EU and of the European Economic Area last published 8 years ago
@MTMSIH Bayesian disease mapping methods for areal data - explains key concepts applied to create an atlas
Explores Australia as a case study, utilising QLD SA2 areas

-->


@SAMGIS suggests it is the "investigators' objectives" that drive the "representation of diseases on maps". There will be situations like infectious diseases that require choropleth methods

### Public face (Jessie)

what has been provided to the public, norms, common practices, all of Jessie's lit review


## Cartograms (Steff)

Cartograms are a thematic map, presenting statistical and geographical information like choropleths. The difference is the augmentation of the geographical areas.
This was originally implemented to allow a map base that represented the populations within regions. 
@HEDP argues that 'cancer occurs in people, not in geographical areas' and the map base should reflect this to avoid allocating 'undue prominence' to rural areas. It makes areas with greater populations bigger on the map space, but kept relationship with neighbours.
@DMAHP reduce the visual impact of large areas with small populations. The distortion of spatial areas is proportional to the denominator variable. This is implemented in an iso-demographic map, for approx equal population density.


Geographical and demographic base maps could be implemented after digital computer methods became available. Alternatively, the area on the map space can represent the value. There have been many algorithms presented, @SAIC investigate these implementations and the "statistical accuracy, geographical accuracy, and topological accuracy".

@HEDP shows the introduction of electronic computer-assisted techniques created a flood of disease atlases like Howe's National Atlas of Disease Mortality in the United Kingdom (Howe 1963) which upgraded to a demographic base "map" (Howe 1970).


@MTMSIH to uncover local-level inequalities frequently masked by health estimates from large areas


### Contiguous

<!-- Compress this to 2 sentence introduction about methods. Focus on which atlases have implemented this technique.--->
Cartograms keep spatial relationships of neighbours intact by keeping borders when adjusting sizes.
From a computer graphics perspective it is a problem of 'map deformation' to account for the value assigned to each area. @ACA discuss their implementation of three methods for creating value - by - area cartograms. @ECGC present the problem of maintaining shape presevation in non-contiguous cartograms.
 
The intention is to allow the map space to highlight the distribution of the variable. However drawing attention to large value areas and allowing reader to see all significant areas on a map, relies on them also knowing the difference between initial geography and new layout given by a cartogram.
Importance of the statistic in this area being communicated was more important than keeping geography recognisable.

eg. state by population

Australia (McGlashan 1977),

We were able to create cartograms by access to data, access to tools, greater demand for insights.

In theory these ideas have been used, but the people making them do not necessarily have not access or ability to create them.

Therefore the uptake of these maps has been due to education, not the validity of their use.

### Non-Contiguous

Dorling (Sized according to statistic)

Used in displays of the UK by Howe in 1986 cited by @HEDP
<!--
## Temporal displays
-->

@TFYCC Value-Area Cartograms. In these cartograms a region,country, or continent is subdivided into small regions, each ofwhich is represented by a rectangle. This rectangle is proportionate in area to the value which it represents in certain statistical distributions. The regions are grouped in approximately the same positions as they are on the map.

@CVBGSD presents bivariate maps, using size and colour for different variables.

Computer generated map examples:  @HEDP
(Hopps et al. 1968; Armstrong 1972). There
has followed a flood of disease atlases, mainly concentrating on the modem problems of cancer and degenerative diseases from countries as scattered as the United States (Burbank 1971; Mason et al. 1975, 1976; Pickle et al. 1987), the Soviet Union (Levin 1980), Japan (Shigematsu 1977), the Federal Republic of Germany

### Centroid displays

Plotting centroids on top of geographies. (Size is kept constant)
Hex maps

If the goal of the map is the statistic.

If the distribution is the focus, the display should reflect that.

Replies on the idea that every area is important, no matter the size.

Recent methods have every area represented with the same map space.

This gives equal emphasis to every area, allows distributions and relationships between neighbours to become more clear.

## A critique choropleth and cartograms

(only worth including if it is possible for us to implement)
Tabular form comparing and contrasting
- Relationship to geography

- Show using cancer examples

## Animation

lends to temporal pattern exploration

@ECGC ?? Highlight the value of animating contigous to see changes over time, US can be recognisable but animation aides interpretation 

## Acknowledgements

What software did we use, for eg

## References

<!--
## Software
Commonly available tools to implement.
-->

<!--
### counts versus predictions

@SEMA
'Disease mapping is carried out to summarise spatial and spatio-temporal variation in risk.'
Descriptive statistic of the relationship between geography and a disease.
population, exposure, and health data may have point data or aggregated summaries (count data)
potentially be subject to a number of inaccuracies
diagnostic error or misclassification

Not only the counts, but population, migration, deaths and births are modelled across census years.

rapid visual summary of complex geographical information, descriptive purposes, to generate hypotheses, for surveillance, and to aid policy formation and resource allocation.

When using counts:
 small populations imply large variability in estimated rates
 
Decisions taken at this stage may be critical as apparent ‘clusters’ may depend crucially on the boundaries chosen in time or space: ‘The more narrowly the underlying population is defined, the less will be the number of expected cases, the greater will be the estimate of the excess rate, and often the more pronounced will be the statistical significance’ 
 
Using prediction:
assuming that neighbouring μi are correlated leads to a ‘clustering’ prior




Driven by progressions in computing, statistical methods and collection of data.

Models summarise relationships between counts of diseases and other factors.

Choropleth Maps, relationship between regions and spatial location. Able to represent all the occurrences within areas more cohesively, as total counts, or colours.


Urbanisation pushed people closer together, in workplaces and in homes.

Recognition of biases when utilising the geography to map people. Small areas contain more people, work towards representing regions of importance more clearly.
-->



