---
from: Stephanie Kobakian
fromqualifications: BA
fromtitle: Research Masters Student
fromemail: stephanie.kobakian@monash.edu
fromphone: +61 433 699 797
fromsignature: sigfile.png
toname: Professor Peter Baade and Dr Susanna Cramb
opening: Dear Professor Peter Baade and Dr Susanna Cramb,
closing: Warm regards
spacing: 1.4
output: MonashEBSTemplates::letter
---

Thank you for your letter containing your feedback regarding our submision "Cartogram Mapping and its Application to Cancer Data Visualization", for inclusion in the Focused Issue on Spatial Patterns in Cancer Epidemiology in the Annals of Cancer Epidemiology.

This review paper presented an exploration of cancer mapping methods, focusing on variations on choropleths for online cancer atlases.

**Editor suggestion:**
**We would suggest that the aim of the manuscript could be phrased to highlight the current approaches and limitations of typical visualisation methods for cancer maps, along with outlining possible alternative methods and challenges in implementing these?**

We have restructed our original submission to provide a clear path from current approaches used, to the alternative approaches that should be explored. We highlight the limitations of using current display methods, to encourage the use of alternative display methods. We also present the challenges that may be faced when implementing the alternative designs.

The manuscript title has been changed:
"Cancer Applications of Choropleth Maps, and the Potential of Cartograms and Alternative Map Displays"

The manuscript now contains the following sections:

**Traditional approaches for cancer map displays:** This section discusses the choropleth map as the common map display used in cancer maps and atlases.
*Limitations of choropleth displays:* This section presents the possible issues with displaying cancer statistics on a choropleth map.
*Contemporary alternatives to choropleth maps:* We have shown that there are many alternative displays that highlight population dense regions.
*Challenges of alternative approaches:* Alternative displays also have limitations when displaying spatial distributions of cancer statistics.



We have inclued changes to reflect your minor notes:

*Editor suggestion:*
*The authors mention a focus on Atlases published between 2010 and 2015, but then include a bowel cancer atlas from 2016. *

*Also, within the bowel cancer atlas data, the reporting of percent of males aged 50-54 with bowel cancer in 2016 is incorrect; it should be the % of the ERP in each area that are males aged 50-54 years. *

We have changed the image used from the Bowel Cancer Atlas. To reflect this change the description of the statistic used in the bowel cancer atlas of Australia ahs been corrected:


Bowel Cancer Australia Atlas:
...shows the average Standardised Incidence Ratio of colorectal cancer for Australian males from 2006 to 2010 in Australia. It is published by Bowel Cancer Australia https://www.bowelcanceraustralia.org/.  


The following section outlines comments made by the reviewer and contains our responses after the suggested changes were implemented.

*Reviewer A: *
*Major*
*Comment 1: *
The Abstract should be more focused- perhaps give an example of how cartogram mapping has been applied to data visualisation. What are the benefits of this approach and suggestions for the future.

*Reply 1:* 
The advantages of alternative mapping displays, including cartograms, has been included in the abstract. It clearly includes the changes to the map display made by alternative visualisation methods, and how they benefit the map user as they build an understanding of the spatial distribution.


*Changes in the text:* 

Cancer atlases communicate cancer statistics over geographic domains, typically with a choropleth map. They subdivide these domains into administrative regions such as countries, states, or suburbs. When communicating human-related statistics, the choropleth has a disadvantage in that it draws attention to sparsely populated rural areas to the neglect of small inner city areas. The smaller geographic areas are important to consider if they are densely populated. Alternative map displays, such as a cartogram or a hexagon tile map, can shift the attention of map users from the large rural areas by decreasing their size on the map display. This means alternative displays can be more effective at accurately communicating spatial patterns across spatial areas, by highlighting areas of interest. It is recommended that alternative displays are included in cancer atlases. In addition, with the ease of today's technology, user interaction with the displays is encouraged. Users should also be able to interactively display different statistics, such as incidence rate or relative incidence. 


*Comment 2: *

2. The key message seems to get lost in the Abstract. The Conclusion is vague.

*Reply 2:* 
Changes to the abstract have been made. Additionally, the conclusion has also been edited to be more direct in recommending the use or consideration of the alternatives presented.

*Changes in the text:* 
Please see the response to *Comment 1*.

*Comment 3: *

3. Entire paper needs substantial English language editing

*Reply 3:* 
Thank you for this point. Substantial time has been taken to improve the language used in this paper.


*Comment 4: *

4. Please avoid the use of sentences which have been used throughout the paper where you start with a reference number: such as “[4] discusses the use of (Map displays for disease data, Line 15-16) They do not make any sense and must be modified.

*Reply:* 
The referencing system was changed to implement the springer-vancouver style. We apologise for the issues this caused when exporting to a Word Document, the text has been modified appropriately.


*Comment 5: *

5. Please provide numbers for Figures and Tables

*Reply 5:* 
this begins the discussion, andNumbers for figures and tables have been corrected. This paper was produced using Rmarkdown, this introduced errors with numbering figures, sections and tables. All numbering has now been manually defined.

*Comment 6: *

6. Please clearly state the primary aim of this paper and structure it accordingly

*Reply 6:* 
The primary aim of this paper is to present alternative map displays as viable visualisation methods for presenting spatial distributions in cancer atlases. A choropleth map is commonly used in practice, it is described and it's limitations are highlighted. The alternative map displays address the limitations of the choropleth map. The methods and the limitations of these alternative displays are discussed.

*Comment 7: *

7. Conclusions must discuss the key focus and conclusions of this paper. 

*Reply 7:* 
Small changes have been made to the conclusion that make the focus of the paper and recommendations clearer. The conclusion has three parts (1) mapping practices, and recommendations, (2) statistics applied and the pros and cons, and (3) user interaction with online maps and the benefits of incorporating this.


*Minor Comments* 

- Please check the use of past and present tense
- There are many minor grammatical errors that need to checked.
- Please edit the last section of the Introduction. Either number each section and then refer to them or find another way to appropriately refer to each section.

All minor comments were addressed in the process of substantial editing.


We thank you for your consideration of our changes.



