---
from: Stephanie Kobakian
fromqualifications: B.Com and B.Eco
fromemail: stephanie.kobakian@monash.edu
fromphone: +61 433 699 797
fromsignature: sigfile.png
toname: Professor Peter Baade and Dr Susanna Cramb
opening: Dear Professor Peter and Dr Susanna,
closing: Warm regards
spacing: 1.4
output: MonashEBSTemplates::letter
---

We recently received the document titled *ACE-19-31-R1-from-the-reviewers*, we thank you for the recommendations and changes made within this document.

Your feedback regarding our submission included a title change, please accept this resubmission with the new title "Mapping Cancer: the Potential of Cartograms and Alternative Map Displays", for inclusion in the Focused Issue on Spatial Patterns in Cancer Epidemiology in the Annals of Cancer Epidemiology.

This review paper presents an exploration of cancer mapping methods, focusing on variations on choropleths for online cancer atlases.

**Reviewer suggestion:**
**Add a sentence about the study aims (in the abstract).**

We have included the following sentence in the abstract:

*This study summarises current practices for cancer atlases and investigates the alternative map displays that could be used to accurately represent the distribution of cancer statistics across a population, as many cancer atlases lack appropriate displays for population statistics.*


**Reviewer suggestion:**
**Could we structure paper as:**
**Introduction (also introduces cancer atlases)**
**Measures mapped (info around Table 2)**
**Visualisation approaches**
**- Choropleth (mention advant and disadvant, along with figures from cancer atlases)**
**- Cartograms**
**- Tile maps**
**- Geofacets**
**- Multivariate maps**
**Comparison & critique of alternative methods**
**Additional considerations**
**- Associated graphs**
**- Displaying uncertainty measures**
**- Interactivity**
**Recommendations for mapping cancer**
**Conclusion**

We have rearranged the sections from the "Introduction" to "Traditional approaches for cancer map displays" in this submission at the request of the reviewer. The discussion of choropleth maps considers the advantages and disadvantages now occurs in the same section.


The following reviewer suggestions relate to the introduction:

**Reviewer suggestion:**
**Given the ethical and privacy considerations for small area data, it is not a straightforward process to obtain and report area-specific counts.**

We agree that it is not easy to obtain and report area-specific counts.
The statement has been removed.

**Reviewer suggestion:**
**Suggest moving paragraph to proposed choropleth maps section**

This paragraph has been moved the choropleth section under visualisation approches.

**Reviewer suggestion:**
**Can you include mention of how this is different to a thematic map?**

We have included in the choropleth section:
Choropleth maps are a type of thematic map that show polygons for each of the groups of data points representing the geographic units, where each polygon is shaded with a color according to the area-specific values of the statistic being conveyed.

**Reviewer suggestion:**
**Suggest also noting development of statistical methods and software**
The paragraph that began the *Cancer Atlases* section has been moved to the introduction. This paragraph describes cancer atlases, and the developments oof statistical methods and software.

**Reviewer suggestion:**
**Give the actual reference for Cruikshank 1947**

This quote has been removed.

**Reviewer suggestion:**
**Suggest including Australian Cancer Atlas**
We have replaced the Bowel Cancer Australia Atlas with the Australian Cancer Atlas.

**Reviewer suggestion:**
**This table might benefit from an additional column, which gives an example of a cancer map using this measure. Also, some of these measures can be calculated.**

Several suggestions were made regarding Table 1: Common measures for reporting cancer information. this table was previously Table 2 and an additional column has been included to indicate the cancer atlas examples in Figure 1 that display each statistic.



**Reviewer suggestion:**
**This is the wrong reference.**
The incorrect reference to the use of Statistical Areas at Level 2 for the Atlas of Cancer in Queensland has been corrected to reflect that the atlas used Statistical Local Areas.

**Reviewer suggestion:**
The following paragraph was included at the suggestion of the reviewer:

As data becomes more sparse, either by increasing geographic resolution or stratifying by age/sex, obtaining reliable estimates becomes more difficult. Many atlases analyzing smaller areas use statistical modelling to produce estimates, although some continue to use simple calculations and suppress regions where estimates are unstable.

**Reviewer suggestion:**
**Are you referring to area-based characteristics?**
This socioeconomic indicators mentioned refer to the characteristics of small areas presented in cancer atlases.
The Australian cancer atlas allows filtering using socioeconomic indicators, but this statement has been removed as it is not common in other atlases.

**Reviewer suggestion:**
**These are very different terms, so ideally should not have the same abbreviation. **
The terms credible intervals and confidence intervals are no longer abbreviated to avoid dual use of the abbreviation.


**Reviewer suggestion:**
**Which map?**
The following sentence has been removed: The map focuses on displaying the statistic and lacks additional space to represent the uncertainty. 
As the Australian Cancer Atlas example presented in Figure 1 does include uncertainty using transparency.


**Reviewer suggestion:**
**Can you clarify whether this recommendation holds when using a ratio measure – which has 1 as the average, and then diverging values higher and lower than the average (eg an SIR).**
Diverging colour schemes have been suggested for this use by Cynthia Brewer, however a ratio measure requires rescaling of the colour space:

When communicating information using colour, a map creator should use a scheme with perceptually uniform color spaces that match equal steps in data space with equal steps in the colour space [@PUCS], a linear color gradient is appropriate for incidence counts and rates, but may not be appropriate for ratio measures.


**Reviewer suggestion:**
**Suggest deleting, or rewording to reflect scientific language. **
The following section was removed:
*Inset maps like in Brisbane city in Figure 1c of the state of Queensland are commonly used to reduce distorted interpretations, but it is a bandaid remedy. For Australia, many, many inset maps would be needed.*


**Reviewer suggestion:**
**Can this sentence be reworded for clarity?**
The following section was removed and the concept of cartograms has been explained in the paragraph that introduced cartograms:

*The “population distribution is often extremely uneven”, making a distortion necessary so that population is more faithfully represented as a uniformly distributed background for the statistic to be presented *


**Reviewer suggestion:**
**Ensure all these refs are included in the list.**
References have been added to credit the original publications of the alternative displays dicussed by Tobler.


**Reviewer suggestion:**
**The information in Figure 2 and Table 3 are complementary, and would be better to be combined.**
The details of the variables and their use in the creation of the cartograms has now been included in the caption of figure 2.


**Reviewer suggestion:**
**This text could be moved to the main text / methods.**
The impact of the changes to the maps has now been included in a paragraph structure. 


**Reviewer suggestion:**
**Could you show an example? (of a completed contiguous cartogram that fully resolved the population transformation of areas)**
Sadly I could not find any packages in R that created a complete contiguous cartogram. Allowing the algorithm to run for further iterations saw the error rise, we chose the amount of iterations that led to the minimum error.

**Reviewer suggestion:**
**This is a subjective comment – maybe “a very large amount of white space”?**
Thank you for the suggestion, the previous text has been replaced with your suggestion.


**Reviewer suggestion:**
**Can you summarise these here? (suggestions and comments to help map creators best communicate their health data and spatial analysis)**

An additional paragraph has been included that dicusses the recommendations made by Bell et al. for choosing desirable alternative map diplays.

*Some mix of tiling, faceting or even micromaps, which allow some spatial continuity while also zooming into small areas, are good solutions for difficult geographies. Bell et al. [@CPISACA] provide suggestions and comments to help map creators best communicate their health data and spatial analysis. The authors highlighted that the map design chosen should be tested on a representative sample of potential consumers, to ensure that the target audience is not misinformed by the display. The authors encourage the consideration of map types beyond the traditional classed choropleth map, but warn that sound cartographic principles must be employed to ensure effective communication to the public. A clear definition of the purpose of the display can help map creators to select the design that best communicates the statistic of interest [@CPISACA]. Table 4 lists several features, or limitations, of each alternative display in contrast to the commonly used choropleth map. The desirable features of each display can be contrasted within the table, this can be used to help inform the choice of map creators as they consider each alternative display. Map creators should choose a display that best communicates the statistic according to the purpose of their display.*

**Reviewer suggestion:**
**Not clear what “sometimes” means (in table 3).**
The use of Yes, No and Possible in the calls of Table 3 has been explained in the new caption:

*Summary of features and constraints of common mapping methods used to display cancer statistics. Yes means that the map dispay always employs the characteristic. No means that the display does not employ the characteristic. Possible means it is possible to employ the characteristic when using the display, but it is not necessary to produce the display.*


**Reviewer suggestion:**
**Suggest either a separate recommendations section or very clearly laying out the recommendations here. Do you recommend always (and only) using alternative visualisations, regardless of the audience, or are you suggesting supplying multiple forms of visualisations? Does your recommendation differ depending on the country/data? Ensure your final recommendations are clearly reflected in your abstract wording also. **

The following paragraph has been included to make clear the recommendations of the authors to the readers.

*Choropleth map displays are familiar and useful for map users to orient themselves to the statistic and additional features of the display. A choropleth map display may be the most effective display for the data considering budget, time, and maintenance contraints. Map creators should consider the shapes and discrepancies in size within the set of geographic units used for analysis, and whether the features of the dataset warrant transformation of the geographic units. Additional mapping methods should be considered by map creators during the development of a cancer atlas, as alternative displays may align better with the purpose of the display. Incorporating the population of the geographic units may better inform the map readers of the distribution of the statistic. The importance and potential impact of utilising a display that emphasises the underlying population should be considered during the design phase. Cartograms and tile maps should be adopted as primary displays going forward, or secondary displays if the familiarity of the choropleth map will benefit the users. Clear explanations of the interpretation of the geogephic units in alternative displays should also be included, along with the features of the distribution of the statistic. *



**Reviewer suggestion:**
**Isn’t the most ‘basic’ the number of cancers?**
We have removed the statement: The most basic is the incidence rate. 


**Reviewer suggestion:**
**Crude or age standardized?**
We have clarified that the age standardized rates are of interest here.


**Reviewer suggestion:** XXX
I would suggest replacing this section with a discussion of relative versus absolute measures. 






All minor comments including spell checking and grammar fixes were addressed in the process of editing.


We thank you for your consideration of our changes.



