---
from: Stephanie Kobakian
fromqualifications: B.Comm. and B.Eco.
fromtitle: Research Masters Student
fromWWW: srk.netlify.com
fromemail: Stephanie.Kobakian@monash.edu
fromphone: +61 433 699 797
fromsignature: sigfile.png
toname: Editors-in-Chief
opening: Dear Editors-in-Chief Dr Freddie Bray and Dr Wanqing Chen,
closing: Warm regards
spacing: 1.4
output: MonashEBSTemplates::letter
---

Please consider our review paper titled "Cartogram Mapping and its Application to Cancer Data Visualization", for inclusion in the Focused Issue on Spatial Patterns in Cancer Epidemiology in the Annals of Cancer Epidemiology.

We were honoured to receive the request from Drs. Baade and Cramb, and Editor Kathryn Yan, to explore the use of mapping methods to present cancer statistics.
This review paper presents an exploration of cancer mapping methods, considering the use of choropleths in many current online cancer atlases.
It highlights the current uses of interactivity and how this allows users to engage with cancer statistics in an online atlas.

This manuscript encourages those who produce atlases to consider cartograms and other alternative displays that effectively communicate cancer outcomes.
We believe that this manuscript is a good fit for the Annals of Cancer Epidemiology, as it encourages careful consideration of the mapping methods used to present spatial information, we expect that this exploration will be of interest to readers of the journal. We hope this will inspire the creation and improvement of cancer atlases worldwide.

We thank you for your consideration.


